name: scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 10 * *'

jobs:
  virus-total:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Build Binaries
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 'v2.9.0'
          args: build --snapshot
      - name: List binaries
        run: |
          ls -lh ./dist/punchout_*/punchout
      - uses: dhth/composite-actions/.github/actions/scan-files@main
        with:
          files: './dist/punchout_*/punchout'
          vt-api-key: ${{ secrets.VT_API_KEY }}
